In [74]:
import pandas as pd
import numpy as np 

In [75]:
data = pd.read_csv("Churn_Modelling.csv");

In [76]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [77]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [78]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [79]:
data = data.drop(["RowNumber" , "CustomerId" , "Surname"],axis = 1)

In [80]:
data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [81]:
data.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

In [82]:
for column in data.columns:
    if(column=="CreditScore"):
        continue
    else:
        print(data[column].unique())

['France' 'Spain' 'Germany']
['Female' 'Male']
[42 41 39 43 44 50 29 27 31 24 34 25 35 45 58 32 38 46 36 33 40 51 61 49
 37 19 66 56 26 21 55 75 22 30 28 65 48 52 57 73 47 54 72 20 67 79 62 53
 80 59 68 23 60 70 63 64 18 82 69 74 71 76 77 88 85 84 78 81 92 83]
[ 2  1  8  7  4  6  3 10  5  9  0]
[     0.    83807.86 159660.8  ...  57369.61  75075.31 130142.79]
[1 3 2 4]
[1 0]
[1 0]
[101348.88 112542.58 113931.57 ...  42085.58  92888.52  38190.78]
[1 0]


In [83]:
from sklearn.preprocessing import LabelEncoder;

label_encoder = LabelEncoder()
data["GenderEncoded"] = label_encoder.fit_transform(data["Gender"])
data["GenderEncoded"].head()



0    0
1    0
2    0
3    0
4    0
Name: GenderEncoded, dtype: int64

In [84]:
data["Gender"] = data["GenderEncoded"]

In [85]:
data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  GenderEncoded  
0          1               1        101348.88       1              0  
1          0               1        112542.58       0              0  
2          1               0        113931.57       1              0  
3          0               0         93826.63       0              0  
4          1               1         79084.10       0              0

In [86]:
data = data.drop("GenderEncoded" , axis = 1)

In [87]:
data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [88]:
import pickle
with open("label_encoder.pkl" , "wb") as file:
    pickle.dump(label_encoder, file)

In [89]:
from sklearn.preprocessing import OneHotEncoder

geo_encoder = OneHotEncoder()

geo_converted = geo_encoder.fit_transform(data[["Geography"]]).toarray()
geo_converted

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [90]:
geo_converted_df = pd.DataFrame(geo_converted , columns=geo_encoder.get_feature_names_out(["Geography"]))
geo_converted_df

Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [91]:
with open("geo_encoder.pkl" , "wb") as file:
    pickle.dump(geo_encoder , file)

In [92]:
data = pd.concat([data.drop("Geography",axis = 1) , geo_converted_df], axis = 1)
data.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   
3               0         93826.63       0               1.0   
4               1         79084.10       0               0.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0  
1                0.0              1.0  
2                0.0              0.0  
3                0.0              0.0  
4                0.0              1.0

Now create the deep learning model

In [93]:
data.shape

(10000, 13)

total 13 columns are there and we have to train on 12 clumns as 1 columns is our train column datasaet


In [94]:
X = data.drop("Exited",axis =1)
y = data["Exited"]

In [95]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X , y , test_size=0.2,random_state=1,stratify=y)

In [96]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [97]:
with open("scaler.pkl" , "wb") as file:
    pickle.dump(scaler,file)

In [98]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping , TensorBoard
import datetime

In [99]:
(X_train.shape[1],)

(12,)

In [100]:
model=Sequential([
    Dense(units=64,activation="relu", input_shape=(X_train.shape[1],),name="H_1"),
    Dense(units=32,activation="relu",name="H_2"),
    Dense(units=1,activation="sigmoid",name="output")
])

c:\Users\Shree\anaconda3\envs\myenv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [101]:
model.compile(optimizer="adam",loss="binary_crossentropy" , metrics=["accuracy"])

In [102]:
log_dir = "log/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir , histogram_freq=1)

In [103]:
callback = EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [104]:
history= model.fit(x=X_train , y = y_train , validation_data=(X_test,y_test) , epochs=100 , callbacks=[tensorflow_callback , callback] )

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 11ms/step - accuracy: 0.7937 - loss: 0.4936 - val_accuracy: 0.8285 - val_loss: 0.4003
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8360 - loss: 0.3872 - val_accuracy: 0.8530 - val_loss: 0.3736
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8558 - loss: 0.3576 - val_accuracy: 0.8565 - val_loss: 0.3670
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8633 - loss: 0.3510 - val_accuracy: 0.8565 - val_loss: 0.3597
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8599 - loss: 0.3369 - val_accuracy: 0.8625 - val_loss: 0.3585
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8646 - loss: 0.3331 - val_accuracy: 0.8490 - val_loss: 0.3621
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8591 - loss: 0.3359 - val_accuracy: 0.8565 - val_loss: 0.3597
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8637 - loss: 0.3276 - val_acc

In [106]:
model.save("model.h5")

In [107]:
%load_ext tensorboard

In [109]:
%tensorboard --logdir log/fit

Reusing TensorBoard on port 6006 (pid 11036), started 0:04:20 ago. (Use '!kill 11036' to kill it.)